### ISSUE TITLE
Extend VM disk size

### ISSUE THREAD

**Issue by qkfrksvl** [kubevirt/hostpath-provisioner#164]
Without distribute storage, the only option is that local storage such as local-path provisioner, host-path provisioner.
I have two question regarding these provisioner.

First, is there any method to extend VM disk on hostpath-csi driver? it shows that increasing PVC size is only available with dynamic pvc when I tried. and also all of the PVC show the whole size of node disk.

Second, is there any method to select the specific node with local-path provisioner when provisioning VM?
the problem is that CDI pod was creating on wrong host.

**Comment by awels** [comment]
So the reason that hostpath-csi shows the entire disk as the size is that there is no mechanism for one to prevent a pod from writing the entire disk. The hostpath simply creates a directory somewhere, and provides that to the pod. I am guessing you want to increase the disk.img size for your virtual machine?

**Comment by qkfrksvl** [comment]
hi, @awels :) 

yes, I want to increase the disk.img size. and I belive that it lead to that increasing VM os disk size.

**Comment by awels** [comment]
So if the capacity of the PV is already the max disk size, it is kind of hard to resize the PVC or implement PVC resizing since it is maximum by default. CDI knows about this and when it creates the disk.img file it will take the min of PVC request size and PV capacity and create a disk of the correct size.

The simplest way to resize right now would be to use CDI to clone the PVC into a larger one, then CDI will take care of resizing the disk.img. You can also simply manually resize the disk.img with something like qemu-img (which is what CDI does in the back ground)

**Comment by awels** [comment]
I forgot to mention the CDI clone will also allow you to move the disk to a different node if that is important.

**Comment by qkfrksvl** [comment]
it's awsome :) i've checked the qemu-img worked well. you're really kubevirt expert. thank you for always helping me!!! Have a nice day @awels

**Comment by alromeros** [comment]
@qkfrksvl glad everything got figured out! I see the issue is stale, are you ok with us closing this issue?
