### ISSUE TITLE
pv capacity.storage is bigger than pvc requests.storage

### ISSUE THREAD

**Issue by huyinhou** [kubevirt/hostpath-provisioner#33]
**BUG REPORT:**

/kind bug

**What happened**:
Image: quay.io/kubevirt/hostpath-provisioner:latest
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kube-1-hpp-claim
  annotations: 
    kubevirt.io/provisionOnNode: 172.16.0.6
spec:
  storageClassName: "kubevirt-hpp"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

$ kubectl get pvc kube-1-hpp-claim \
    -o custom-columns='REQUEST:.spec.resources.requests.storage,CAPACITY:.status.capacity.storage'
REQUEST   CAPACITY
4Gi       39Gi
```
**What you expected to happen**:
pvc request.storage = pv capacity.storage

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
Hi,

Yes that is actually correct. Since there is no mechanism to prevent whomever is using the PVC to write as much as they want. So lets say the total available space in the volume directory is 100G. and you request a 5G PVC, It will create the directory to back the PVC, and now whomever uses the PVC can write up to 100G if they want.

For that reason, the PV HAS to report 100G size even if you just request a 5G PVC.

This leads to all kinds of weird things if you are not expecting it. Once can create 100 PVs of 'size 100G' on a 100G disk. Obviously you can only write a combined 100G on that disk.

If you look at for instance a bind mounted local volume provisioner, it does the same thing, the PVs are all the maximum available size. PR #4 is what you are trying to revert with your PR.

**Comment by huyinhou** [comment]
Yesterday, when using it with DataVolume, I found that the size of disk.img exceeds pvc request.storage too much.
I tried it again today and found out that the reason is that the storage setting in the PVC is too small.
Read the code again and found that it is not the problem here. Data Importer gets the size set in PVC.
I closed this issue, thanks
